package com.tyss.optimize.common.util;

import java.util.*;

public class CommonConstants {

    public static final Float DEFAULT_VERSION = 1.0f;

    public static final String SHARED_DRIVE = "sharedDrive";
    public static final String ON_PREM = "ONPREM";
    public static final String DEFAULT_PUBLISH_VERSION = "1.0";
    public static final Float NEW_VERSION = 0.0f;
    public static final String NEW_DEFAULT_VERSION = "0.0";
    public static final String ANONYMOUS_USER = "USR1";
    public static final String MAX_TWO_SUPER_ADMINS_MESSAGE = "More than 2 super admins are not allowed per license";
    public static final String PROJECT_TYPES = "project.types";
    public static final String YES = "Y";
    public static final String NO = "N";
    public static final String ROOT = "Root";
    public static final String STEP_GROUP = "STEP_GROUP";
    public static final String SCRIPTS = "scripts";
    public static final String UPDATE_TAG = "UPDATE";
    public static final String CREATE_TAG = "CREATE";
    public static final String DELETE_TAG = "DELETE";
    public static final String RESOLVE_TAG = "RESOLVE";
    public static final String None = "None";
    public static final String DFC = "DFC";
    public static final String STATE_COMMIT = "COMMIT";
    public static final String STATE_PUBLISH = "PUBLISH";
    public static final String STATE_RB = "ROLLBACK";
    public static final String STATE_REMOVE = "DELETE";

    public static final String DB_ID = "_id";
    public static final String OBJECT_ID = "id";
    public static final String WSWB = "WSWB";
    public static final String LOCAL = "LOCAL";
    public static final String SCRIPT_CHART_WIDTH = "scriptChartWidth";
    public static final CharSequence ROOT_MODULE = "Root Module";
    public static final String NLP_UTIL = "com.tyss.optimize.nlp.util.";
    public static String Hello = "HELLO";
    public static final String EMPTY = "";
    public static final String DOUBLE_COLON = "::";
    public static final String SINGLE_COLON = ":";
    public static final String SINGLE_DOT = ".";
    public static final String FORWARD_SLASH = "/";
    public static final String SINGLE_SPACE = " ";
    public static final String SINGLE_UNDERSCORE = "_";
    public static final String SINGLE_HYPHEN = "-";
    public static final String SINGLE_COMMA = ",";

    public static final String TEST_DEVELOPMENT = "TEST_DEVELOPMENT";

    public static Map<String, String> sequenceGenMap = initMap();
    public static String MODULE_CHART_WIDTH = "moduleChartWidth";

    private static Map<String, String> initMap() {
        Map<String, String> sequenceMap = new HashMap<>();
        sequenceMap.put("PROJECT", "PJT");
        sequenceMap.put("PAGE", "PAG");
        sequenceMap.put("USER", "USR");
        sequenceMap.put("DEFAULT", "DEF");
        sequenceMap.put("ELEMENT", "ELE");
        sequenceMap.put("MODULE", "MOD");
        sequenceMap.put("STEP", "STE");
        sequenceMap.put("SCRIPT", "SCR");
        sequenceMap.put("ROLE", "ROLE");
        sequenceMap.put("USER_ROLE", "USER_ROLE");
        sequenceMap.put("LICENSE", "LIC");
        sequenceMap.put("PACKAGE", "PKJ");
        sequenceMap.put("FOLDER", "FLDR");
        sequenceMap.put("LIBRARY", "LIB");
        sequenceMap.put("STEP_GROUP", "STP_GRP");
        sequenceMap.put("PROGRAM_ELEMENT", "PRG_ELE");
        sequenceMap.put("NLP_METADATA", "NLP");
        sequenceMap.put("NLP", "NLP");
        sequenceMap.put("FILE", "FILE");
        sequenceMap.put("PE_NLP", "PE_NLP");
        sequenceMap.put("PRE_POST_CONDITION", "PE_POST_COND");
        sequenceMap.put("DATA_PROVIDER", "DATA_PROVIDER");
        sequenceMap.put("EMAIL_TEMPLATE", "EMT");
        sequenceMap.put("LABEL_GROUP", "LABEL_GROUP");
        sequenceMap.put("LICENSE_TYPE", "LIC_TYPE");
        sequenceMap.put("LABEL", "LABEL");
        sequenceMap.put("LICENSE_PLAN", "LIC_PLAN");
        sequenceMap.put("LIMIT", "LIMIT");
        sequenceMap.put("PROJECT_TYPE", "PJT_TYPE");
        sequenceMap.put("VARIABLE", "VAR");
        sequenceMap.put("QUICK_RUN_SETTINGS", "QRS");
        sequenceMap.put("EXECUTIONRESPONSE", "EXR");
        sequenceMap.put("DEPENDENT_SCRIPT", "DEP_SCR");
        sequenceMap.put("STEP_GROUP_NLP", "SG_NLP");
        sequenceMap.put("EXECUTION", "EXEC");
        sequenceMap.put("EXECUTION_REQUEST", "EXEREQ");
        sequenceMap.put("PARAMETER", "PARAMETER");
        sequenceMap.put("SUITE", "SUITE");
        sequenceMap.put("SUITE_OF_SUITES", "SOS");
        sequenceMap.put("SHARED_ELEMENT", "SH_ELE");
        sequenceMap.put("RECORDED_ELEMENT", "RD_ELE");
        sequenceMap.put("CLIENT_SYSTEM_CONFIG", "SCDR");
        sequenceMap.put("EMAIL_GROUP", "EMAIL_GROUP");
        sequenceMap.put("VARIABLE_SET", "VARIABLE_SET");
        sequenceMap.put("TEST_DATA_SET", "TEST_DATA_SET");
        sequenceMap.put("LICENSE_DEFAULT", "LIC_DEFAULT");
        sequenceMap.put("DATATYPE", "DTP");
        sequenceMap.put("STORAGE_CONFIG", "STR");
        sequenceMap.put("WAIT_CONFIG", "WT_CFG");
        sequenceMap.put("RESULT_CONFIG", "RES_CFG");
        sequenceMap.put("HISTORY_CONFIGURATION", "HIS_CFG");
        sequenceMap.put("ELEMENT_TYPE", "ELE_TYPE");
        sequenceMap.put("LOCATOR_TYPE", "LOC_TYPE");
        sequenceMap.put("BROWSERSTACK", "BROWS");
        sequenceMap.put("SCREEN_SHOT_VIDEO_CONFIG", "SCR_VIDEO_CFG");
        sequenceMap.put("DEFAULT_PROJECT_ELEMENT", "DEF_PJT_ELE");
        sequenceMap.put("SAUCELABS", "SAUCE");
        sequenceMap.put("DRIVER_CONFIG", "DC");
        sequenceMap.put("SCHEDULE", "SCHE");
        sequenceMap.put("JIRA", "JIRA");
        sequenceMap.put("LAMBDATEST", "LAMBDA");
        sequenceMap.put("TAGDETAIL", "TAG");
        sequenceMap.put("DEFAULT_CONFIGURATIONS", "DCONF");
        sequenceMap.put("STORAGE_DETAIL", "STRC");
        sequenceMap.put("STORAGE_SNAPSHOT", "SNAP");
        sequenceMap.put("SCRIPT_TEMPLATE", "TEMP");
        sequenceMap.put("SLACK", "SLACK");
        sequenceMap.put("GITLAB", "GITLAB");
        sequenceMap.put("GITHUB", "GITHUB");
        sequenceMap.put("DEFECT_TEMPLATE", "DEFTEMP");
        sequenceMap.put("LICENSE_PRIVILEGE", "LIC_PRIV");
        sequenceMap.put("GIT_INSTANCE", "GITINST");
        sequenceMap.put("DEFECT_LIFECYCLE_TEMPLATE", "DEFLIFTEMP");
        sequenceMap.put("RUN_SETTINGS", "RUN_SET");
        sequenceMap.put("LICENSE_RECONCILIATION", "LIC_RECON");

        return Collections.unmodifiableMap(sequenceMap);
    }

    public static String DB_PREFIX = "DB_PREFIX";
    public static String MONGO_AUTH_DB = "MONGO_AUTH_DB";
    public static String SUCCESS = "SUCCESS";
    public static String FAILURE = "FAILURE";
    public static final String TOKEN_INVALID = "Token is invalid/Expired";
    public static final String TOKEN_VALID = "Token is Valid";
    public static final String ALREADY_EXIST = " already exist";
    public static final String DEFAULT_ANDROID_FLD = "Default-Android";
    public static final String DEFAULT_IOS_FLD = "Default-iOS";
    public static final String DEFAULT_ICON = "--";
    public static final String UNAUTHORIZED = "You are not authorized";
    public static final String FULL_ACCESS_ROLE = "Full Access";
    public static final String EXECUTE_ACCESS_ROLE = "Execute Access";
    public static final String DEFAULT_FULL_ACCESS_ID = "ROLE1001";
    public static final String DEFAULT_EXECUTE_ACCESS_ID = "ROLE1002";
    public static final String INACTIVE_USER = "User is not activated"; 
    public static final String ACTIVE_USER = "User is already activated";
    public static final String IS_SECOND_SUPER_ADMIN = "isSecondSuperAdmin";
    public static final String INVALID_USER = "Email or Password is invalid, please try again";
    public static final String STATIC = "static";
    public static final String DYNAMIC = "dynamic";
    public static final String STATE_NEW = "NEW";

    public static final String DEFAULT_EXPORT_PROJECT_FLD = "Export_Project_Json";
    public static final String BUCKET_NAME = "bucketName";
    public static final String STORAGE_TYPE = "storageType";
    public static final String SOURCE_FOLDER_PATH = "sourceFolderPath";
    public static final String EXPORT_REPOSITORY = "repository";
    public static final String EXPORT_EXECUTIONS = "executions";
    public static final String EXPORT_TEMPLATES = "templates";
    public static final String OLD_PROJECT_ID = "oldProjectId";
    public static final String OLD_ROOT_PAGE_ID = "oldRootPageId";
    public static final String OLD_ROOT_LIBRARY_ID = "oldRootLibraryId";
    public static final String OLD_ROOT_FOLDER_ID = "oldRootFolderId";
    public static final String OLD_ROOT_MODULE_ID = "oldRootModuleId";
    public static final String MODULE_ID = "moduleId";
    public static final String LIBRARY_ID = "libraryId";
    public static final String STEP_GROUP_ID = "stepGroupId";
    public static final String DEFAULT_LIBRARY = "defaultLibrary";
    public static final String PAGE_NAME = "name";
    public static final String LIBRARY_NAME = "name";
    public static final String FOLDER_NAME = "name";
    public static final String MODULE_NAME = "name";
    public static final String SUITES_NAME = "name";
    public static final String DEFECT_TEMPLATE_NAME = "name";
    public static final String DEFECT_LIFECYCLE_NAME = "name";
    public static final String DEFECT_TESTCASE_NAME = "name";
    public static final String VARIABLE_NAME = "name";
    public static final String VARIABLE_TYPE = "type";
    public static final String TYPE_JSON = ".json";
    public static final String TYPE_ZIP = ".zip";
    public static final String EXTENSION_ZIP = "zip";
    public static final String TYPE_IMPORT = "Import";
    public static final String TYPE_EXPORT = "Export";
    public static final String TYPE_PAGE = "Page";
    public static final String TYPE_LIBRARY = "Library";
    public static final String TYPE_MODULE = "Module";
    public static final String TYPE_DEFECT = "Defect";
    public static final String TYPE_SUITE = "Suite";
    public static final String ACCESS_PRIVATE = "Private";
    public static final String ACCESS_PUBLIC = "Public";
    public static final String ENTITY_PROJECT_ELEMENTS = "projectElements";
    public static final String ENTITY_PROGRAM_ELEMENTS = "programElements";
    public static final String ENTITY_STEP_GROUPS = "stepGroups";
    public static final String ENTITY_TEST_DATA = "testData";
    public static final String ENTITY_SCRIPTS = "scripts";
    public static final String ENTITY_SUITES = "suites";
    public static final String ENTITY_DEFECTS = "defects";
    public static final String ENTITY_TEST_CASE = "testCase";
    public static final String ENTITY_DEFECT = "defect";
    public static final String STEP_INPUTS = "stepInputs";
    public static final String FILE_PAGE_COUNT = "PageCount";
    public static final String FILE_LIBRARY_COUNT = "LibraryCount";
    public static final String FILE_MODULE_COUNT = "ModuleCount";
    public static final String FILE_DEFECT_COUNT = "DefectCount";
    public static final String FILE_SUITE_COUNT = "SuiteCount";
    public static final String FILE_LIBRARY_ID_MAP = "LibraryIdMap";
    public static final String DEFAULT_EXPORT_FLD = "Export_Script_Files";
    public static final String DEFAULT_JAR_FLD = "Custom-JAR";
    public static final String FINAL_JAR_FLD = "Final-JAR";
    public static final String DEFAULT_DEFECTS_FLD = "DEFAULT_DEFECTS_FLD";
    public static final String DEFAULT_DATATYPE_ID = "DTP1001";
    public static final String DEFAULT_STORAGE_CONFIG_ID = "STR1001";
    public static final String DEFAULT_ELEMENT_ONE = "DEF_ELE1001";
    public static final String DEFAULT_ELEMENT_TWO = "DEF_ELE1002";
    public static final String DEFAULT_ELEMENT_THREE = "DEF_ELE1003";
    public static final String DEFAULT_ELEMENT_FOUR = "DEF_ELE1004";
    public static final String DEFAULT_ELEMENT_FIVE = "DEF_ELE1005";
    public static final String DEFAULT_ELEMENT_SIX = "DEF_ELE1006";
    public static final String DEFAULT_ELEMENT_SEVEN = "DEF_ELE1007";
    public static final String DEFAULT_ELEMENT_EIGHT = "DEF_ELE1008";
    public static final String DEFAULT_ELEMENT_NINE = "DEF_ELE1009";
    public static final String DEFAULT_ELEMENT_TEN = "DEF_ELE1010";
    public static final String DEFAULT_ELEMENT_ELEVEN = "DEF_ELE1011";
    public static final String DEFAULT_ELEMENT_TWELVE = "DEF_ELE1012";
    public static final String DEFAULT_ELEMENT_THIRTEEN = "DEF_ELE1013";
    public static final String DEFAULT_ELEMENT_FOURTEEN = "DEF_ELE1014";

    public static final String DEFAULT_STEPGROUP_ONE = "STP_GRP1001";
    public static final String DEFAULT_STEPGROUP_TWO = "STP_GRP1002";
    public static final String DEFAULT_STEPGROUP_THREE = "STP_GRP1003";
    public static final String DEFAULT_STEPGROUP_FOUR = "STP_GRP1004";
    public static final String DEFAULT_STEPGROUP_FIVE = "STP_GRP1005";
    public static final String DEFAULT_STEPGROUP_SIX = "STP_GRP1006";
    public static final String DEFAULT_PARAMETER_ONE = "PARAMETER1001";
    public static final String DEFAULT_PARAMETER_TWO = "PARAMETER1002";
    public static final String DEFAULT_LIBRARY_WEB = "Open and Close Browser";
    public static final String DEFAULT_LIBRARY_MOBILE = "Open and Close App";
    public static final String DEFAULT_NLP_WEB_OPEN = "OpenBrowser";
    public static final String DEFAULT_NLP_WEB_CLOSE = "CloseBrowser";
    public static final String DEFAULT_NLP_ANDROID_OPEN = "Open Android App";
    public static final String DEFAULT_NLP_ANDROID_CLOSE = "Close Android App";
    public static final String DEFAULT_NLP_IOS_OPEN = "Open iOS App";
    public static final String DEFAULT_NLP_IOS_CLOSE = "Close iOS App";
    public static final String DEFAULT_NLP_WEB_SERVICE = "RunWebService";
    public static final String WEB_SERVICE_VAR_START_WITH = "WSWB_";
    public static final String WEB_SERVICE_VAR_END_WITH = "_VAR";
    public static final String BROWSER_LIBRARY_ID = "browserLibId";
    public static final String APP_LIBRARY_ID = "appLibId";
    public static final String BROWSER_OPEN_SG_ID = "openBrowserSGId";
    public static final String BROWSER_CLOSE_SG_ID = "closeBrowserSGId";
    public static final String ANDROID_OPEN_SG_ID = "openAndroidSGId";
    public static final String ANDROID_CLOSE_SG_ID = "closeAndroidSGId";
    public static final String IOS_OPEN_SG_ID = "openIOSSGId";
    public static final String IOS_CLOSE_SG_ID = "closeIOSSGId";
    public static final String BROWSER_NAME = "browserName";
    public static final String DEVICE_NAME = "deviceName";
    public static final String URL = "URL";
    public static final String PLATFORM_NAME = "platformName";
    public static final String PLATFORM_NAME_ANDROID = "platformNameAOS";
    public static final String PLATFORM_NAME_IOS = "platformNameiOS";
    public static final String APP_PACKAGE = "appPackage";
    public static final String APP_ACTIVITY = "appActivity";
    public static final String BUNDLE_ID = "bundleID";
    public static final String CAPABILITY = "cap";
    public static final String BASE_URI = "baseUri";
    public static final String PORT = "port";
    public static final String KEY = "key";
    public static final String VALUE = "value";

    public static final String DEFAULT_LOCATORS = "Default Locators";
    public static final String DEFAULT_WAIT_CONFIG = "WT_CFG1000";
    public static final String DEFAULT_RESULT_CONFIG = "RES_CFG1000";
    public static final String DEFAULT_SCREEN_SHOT_VIDEO_CONFIG = "SCR_VIDEO_CFG1000";
    public static final String DEFAULT_HISTORY_CONFIG = "HIS_CFG1000";
    public static final String DEFAULT_DATE_TIME_CONFIG = "DATE_TIME_CFG1000";
    public static final String DEFAULT_MEMORY_CONFIG_ID = "MEM_CFG1000";
    public static final String DEFAULT_CONFIGURATIONS_ID = "DF_CONFS1000";

    public static final Integer FILENAME_MAX = 25;
    public static final Integer FILENAME_MIN = 2;
    public static final String FILENAMESIZE_ALERT = "File name must be minimum " + FILENAME_MIN + " characters";

    public static final Integer PARAM_NAME_MAX = 25;
    public static final Integer PARAM_NAME_MIN = 3;
    public static final String PARAM_NAME_SIZE_ALERT = "Parameter name must be minimum " + PARAM_NAME_MIN + " and maximum " + PARAM_NAME_MAX + " characters";

    public static final Integer COMPONENTS_COUNT_MIN = 5;

    public static final Integer SCREEN_SHOT_MIN_DAYS = 365;
    public static final Integer VIDEO_MIN_DAYS = 365;

    public static final Double TOTAL_MEMORY = 10.0;
    public static final Double FS_TOTAL_MEMORY = 20.0;
    public static final String TOTAL_MEMORY_UNIT = "GB";
    public static final String DEFAULT_MEMORY_UNIT = "MB";
    public static final Double USED_MEMORY = 0.0;
    public static final String USED_MEMORY_UNIT = "GB";
    public static final Double AVAILABLE_MEMORY = 10.0;
    public static final Double FS_AVAILABLE_MEMORY = 20.0;
    public static final Double DEFAULT_PROJECT_MEMORY = 200.0;
    public static final String AVAILABLE_MEMORY_UNIT = "GB";
    public static final Integer PROJECT_COUNT_MIN = 0;
    
    public static Map<String, String> storageUnitMap = initStorageMap();

    private static Map<String, String> initStorageMap() {
        Map<String, String> storageMap = new HashMap<>();
        storageMap.put("GB", "GB");
        storageMap.put("TB", "TB");
        storageMap.put("MB", "MB");
        return Collections.unmodifiableMap(storageMap);
    }

    public static final String DEFAULT_DATE_FORMAT = "dd-mm-yyyy";
    public static final String DEFAULT_DATE_SEPARATOR = "-";
    public static final String DEFAULT_TIME_FORMAT = "hh-mm-ss";
    public static final String DEFAULT_TIME_ZONE = "(UTC+05:30) Chennai,Kolkata,Mumbai,New Delhi";

    public static final String DEFAULT_VIEW_NAME = "Default_View";
    public static final String DEFAULT_VIEW_ALL_COLUMNS = "noOfElements,sharedElements,elementType,version,newCommitPublish,locators,lastModifiedBy,delete,createdBy,createdOn,lastModifiedOn,description";

    public static final Integer COMPONENTS_RESULT_MIN = 200;

    public static final Double EXPLICIT_WAIT = 20.0;
    public static final String EXPLICIT_WAIT_UNIT = "seconds";
    public static final Double IMPLICIT_WAIT = 20.0;
    public static final String IMPLICIT_WAIT_UNIT = "seconds";
    public static final Double DELAY_BETWEEN_STEPS = 0.0;
    public static final String DELAY_BETWEEN_STEPS_UNIT = "seconds";

    public static final Integer RD_ELEMENT_NAME_MAX = 100;
    public static final Integer RD_ELEMENT_NAME_MIN = 2;
    public static final String RD_ELEMENT_NAME_SIZE_ALERT = "Recorded Element name must be minimum " + RD_ELEMENT_NAME_MIN + " and maximum " + RD_ELEMENT_NAME_MAX + " characters";


    // AUTH ROLES
    public static final String FULL_ACCESS = "FULL_ACCESS";
    public static final String NO_ACCESS = "NO_ACCESS";
    public static final String VIEW = "VIEW";
    public static final String WRITE = "WRITE";

    public static final List<String> fancyTreeFolderList = Arrays.asList("PAG", "LIB", "MOD", "FLDR", "EXR", "PKJ", "FLD");
    public static final List<String> timeInSecondsUnit = Arrays.asList("Secs", "Seconds", "Secs.", "seconds", "s");
    public static final List<String> timeInMilliSecondsUnit = Arrays.asList("MilliSeconds", "Milliseconds", "MilliSec", "Msecs", "milliseconds", "ms");
    public static final List<String> timeInHoursUnit = Arrays.asList("Hours", "Hrs.", "hrs");
    public static final List<String> timeInMinutesUnit = Arrays.asList("Minutes", "Mins.", "min");
    public static final List<String> envToValidate = Arrays.asList("Localhost", "Local", "localhost", "local");

    //Execution Client related Constants
    public static String API = "/optimize";
    public static String version = "/v1";
    public static String baseUrl = API + version;
    public static String successMsg = "Success";
    public static String failMsg = "Failed";
    public static String badRequest = "Bad Request";
    public static String alreadyExist = "Already Exist";
    public static String notFoundMsg = "Data Not Found";
    public static Integer successCode = 0;
    public static Integer errorCode = -1;
    public static String nullValue = null;
    public static String running = "Running";

    public static String pending = "Pending";
    public static String REQUEST_FAILED = "Initialization Failed";
    public static String completed = "Completed";
    public static String busy = "Busy";
    public static String available = "Available";
    public static String SCHEDULED = "Scheduled";
    public static String aborted = "Aborted";
    public static final String pass = "PASS";
    public static final String fail = "FAIL";
    public static final String skip = "SKIP";
    public static final String NA = "N/A";
    public static final String warning = "WARNING";
    public static String preCondition = "preCondition";
    public static String postCondition = "postCondition";
    public static String executionEntityResponses = "executionEntityResponses";
    public static String dependantExecutionEntityResponses = "dependantExecutionEntityResponses";
    public static String dot = ".";
    public static String script = "Script";
    public static String module = "Module";
    public static String group = "Group";
    public static String step = "step";
    public static String booleanTrue = "true";
    public static String booleanFalse = "false";

    public static String reports = "./Reports/";
    public static String ifCondition = "IfCondition";
    public static String elseIfCondition = "ElseIfCondition";
    public static String elseCondition = "ElseCondition";
    public static String endIfCondition = "EndIfCondition";
    public static String endElseIfCondition = "EndElseIfCondition";
    public static String endElseCondition = "EndElseCondition";
    public static String parentIfCondition = "parentIfCondition";
    public static String stepName = "stepName";
    public static String conditionName = "conditionName";
    public static String conditionStatus = "conditionStatus";
    public static String END_CONDITION = "endCondition";
    public static String dollar = "$";
    public static String colon = ":";
    public static String openCurlyBrace = "{";
    public static String closeCurlyBrace = "}";
    public static String underScore = "_";
    public static String forwardSlash = "/";
    public static String iteration = "Iteration";
    public static String forCondition = "ForCondition";
    public static String endIteration = "EndIteration";
    public static String endForCondition = "EndForCondition";
    public static String dataProviderName = "dataProviderName";
    public static final String typeBoolean = "java.lang.Boolean";
    public static final String typeInteger = "java.lang.Integer";
    public static final String typeLong = "java.lang.Long";
    public static final String typeShort = "java.lang.Short";
    public static final String typeByte = "java.lang.Byte";
    public static final String typeCharacter = "java.lang.Character";
    public static final String typeFloat = "java.lang.Float";
    public static final String typeDouble = "java.lang.Double";
    public static final String typeString = "java.lang.String";
    public static final String typeListOfString = "List<String>";
    public static final String typeJSONObject = "org.json.simple.JSONObject";
    public static String responseToServer = "Execution request is received and being processed";
    public static final String ifConditionNlpName = "IfCondition";
    public static final String endIfConditionNlpName = "EndIfCondition";
    public static final String elseIfConditionNlpName = "ElseIfCondition";
    public static final String endElseIfConditionNlpName = "EndElseIfCondition";
    public static final String elseConditionNlpName = "ElseCondition";
    public static final String endElseConditionNlpName = "EndElseCondition";
    public static final String startIterationNlpName = "StartIteration";
    public static final String endIterationNlpName = "EndIteration";
    public static final String startForLoopNlpName = "StartForLoop";
    public static final String endForLoopNlpName = "EndForLoop";
    public static final String typeLocal = "LOCAL";
    public static final String typeGlobal = "GLOBAL";
    public static final String typeStepGroup = "STEPGROUP";
    public static final String typeDataProvider = "DATAPROVIDER";
    public static final String typeProjectEnvironment = "PROJECTENVIRONMENT";
    public static final String projectEnvironmentType = "PROJECT_ENVIRONMENT";
    public static String tillLastRow = "Till Last Row";
    public static String systemId = "systemId";
    public static String startIterationCount = "startIterationCount";

    public static String IDENTIFIERs = "http://";
    public static String serverSideExecutionResponseURI = "/optimize/v1/executionResponse";
    public static String clientSystemConfigUpdateExecutionStatusURI = "/optimize/v1/clientSystemConfig";
    public static String token = "token";
    public static String serverHost = "serverHost";
    public static String serverPort = "serverPort";
    public static String resultSyncPort = "resultSyncPort";
    public static String RESOURCE_NAME = "/optimize/v1/executions/result";
    public static String dashboardResourceName = "/optimize/v1/dashboard/execution";
    public static String dashboardStorageResourceName = "/optimize/v1/project/dashboard/storage/";
    public static String licensePrivilegeResourceName = "/appmanagement/optimize/v1/license/privileges";
    public static String projectResourceName = "/optimize/v1/projects/";
    public static String moduleResourceName = "/optimize/v1/modules/";
    public static String publicProjectResourceName = "/optimize/v1/public/";
    public static String projectPort = "8202";
    public static String analyticsResourceName = "/optimize/v1/analytics";
    public static String authResourceName = "/optimize/v1/keycloak";

    public static String terminated = "Terminated";
    public static String partiallyExecuted = "Partially Executed";
    public static String cancelled = "Cancelled";
    public static final String enabled = "enabled";
    public static final String disabled = "disabled";
    public static final String Web = "Web";
    public static final String Android = "Android";
    public static final String AndroidAndIos = "Android & iOS";
    public static final String iOS = "iOS";
    public static final String Webservice = "Webservice";
    public static final String Database = "Database";
    public static final String WebAndMobile = "Web & Mobile";
    public static final String Mobile = "Mobile";
    public static final String Salesforce = "Salesforce";

    public static final String DEFAULT_LOCATOR_ID = "LIC_DEFAULT1001";
    public static final String DEFAULT_LOCATOR_IDS = "LIC_DEFAULT1002";
    public static final String DEFAULT_DYNAMIC_LOCATOR_IDS = "LIC_DEFAULT1003";
    public static final String DEFAULT_VIEW = "DEF_VIEW1001";
    public static final int DEFAULT_LIMIT = 10;
    public static String licenseId = "licenseId";
    public static final String milliSeconds = "MiliSeconds";
    public static final String seconds = "Seconds";
    public static final String forFailedStepsOnly = "For failed steps only";
    public static final String dontCapture = "Don't capture";
    public static String individualType = "INDIVIDUAL";
    public static String suiteType = "SUITE";
    public static String suiteOfSuiteType = "SUITE_OF_SUITES";
    public static String SECRET_KEY = "8my0_4super7_1secret1_5key8";
    public static String SALT = "7X57CKG72JVNSSS9";
    public static String BROWSER = "browser";
    public static String Internet_Explorer = "internet explorer";
    public static String Safari = "safari";
    public static String Firefox = "firefox";
    public static String Microsoft_Edge = "microsoft edge";
    public static String Chrome = "chrome";
    public static String Device = "device";
    public static String Windows = "windows";
    public static String IExplorer = "internet explorer";
    public static String MSedge = "MicrosoftEdge";
    public static String MAC = "mac";
    public static String Linux = "linux";
    public static String Darwin = "darwin";
    public static String internet = "Internet";
    public static String intranet = "Intranet";
    public static String topicPrefix = "consumer-";
    public static String processed = "Processed";
    public static String active = "Active";
    public static String change_password = "change-password";
    public static String otp_verification = "otp-verification";
    public static String inactive = "Inactive";
    public static String once = "Once";
    public static String daily = "Daily";
    public static String weekly = "Weekly";
    public static String monthly = "Monthly";
    public static String yearly = "Yearly";
    public static String CASCADED = "cascaded";
    public static String NOT_CASCADED = "not_cascaded";
    public static String onlyForFailedSteps = "Only for failed Steps";
    public static String execution = "execution";
    public static final int HISTORY_MIN = 5;
    public static final int HISTORY_MAX = 200;
    public static final int SCREEN_SHOT_MIN = 1;
    public static final int SCREEN_SHOT_MAX = 365;
    public static String testData = "testData";
    public static String screenshots = "screenshots";
    public static String videos = "videos";
    public static String programElement = "programElement";
    public static String ADMIN = "ADMIN";
    public static String programElementJar = "tyss-programelements.jar";
    public static String hubUrlPrefix = "https://";
    public static String osName = "Windows";
    public static String parallel = "Parallel";
    public static String sequential = "Sequential";
    public static String distribute = "Distribute";
    public static String license = "License";
    public static String bytes = "B";
    public static String kilo_byte = "KB";
    public static String mega_byte = "MB";
    public static String giga_byte = "GB";
    public static String tera_byte = "TB";
    public static String BROWSER_STACK_CREDENTIALS_URL = hubUrlPrefix + "api.browserstack.com/automate/browsers.json";
    public static String BROWSER_STACK_UPLOAD_FILE_URL = hubUrlPrefix + "api-cloud.browserstack.com/app-automate/upload";
    public static String BROWSER_STACK_GET_FILES_URL = hubUrlPrefix + "api-cloud.browserstack.com/app-automate/recent_apps";

    public static String LAMBDA_TEST_BROWSER_LIST_URL = hubUrlPrefix + "api.lambdatest.com/automation/api/v1/platforms";
    public static String LAMBDA_TEST_UPLOAD_FILE_URL = hubUrlPrefix + "api.lambdatest.com/automation/api/v1/user-files";
    public static String LAMBDA_TEST_GET_FILES_URL = hubUrlPrefix + "api.lambdatest.com/automation/api/v1/user-files";

    public static String SAUCE_LAB_BROWSER_LIST_URL = hubUrlPrefix + "api.us-west-1.saucelabs.com/rest/v1/info/platforms/all";
    public static String SAUCE_LAB_CREDENTIALS_URL = ".saucelabs.com/team-management/v1/teams";
    public static String SAUCE_LAB_UPLOAD_FILE_URL = ".saucelabs.com/v1/storage/upload";
    public static String SAUCE_LAB_GET_FILES_URL = ".saucelabs.com/v1/storage/files";
    public static String GIT_LAB_URL_VALIDATION = hubUrlPrefix + "gitlab.";
    public static String GIT_LAB_URL_EXTENSION = "/api/v4/personal_access_tokens";

    public static String PRE_PROD_HOST_NAME="preprod.fireflink.com";
    public static String PROD_HOST_NAME="backend1.fireflink.com";
    public static String PROD_DEMO_HOST_NAME="prod.fireflink.com";
    public static String fireCrowd = "FireCrowd";
    public static String fireflink = "FireFlink";
    public static String activation = "activation";
    public static String changePwd = "changePwd";
    public static  String HTTP="http";
    public static String HTTPS="https";
    public static String manual = "Manual";
    public static String automation = "Automation";
    public static String automation_and_manual = "Automation and Manual";
    public static String userDefined = "Userdefined";
    public static String preDefined = "Predefined";

    public static final String PROJECT_NAME = "name";
    public static final String PROJECT_ID = "projectId";
    public static final String PROJECT_TYPE = "projectType";
    public static final String PLATFORM = "platform";
    public static final String SEARCH_KEY = "searchKey";
    public static final String TOKEN_INVALID_ERROR = "TOKEN_INVALID ";
    public static final String MODIFIED_BY = "modifiedBy";
    public static final String MODIFIED_ON = "modifiedOn";
    public static final String MODIFIED_BY_UNAME = "modifiedByUname";
    public static final String CREATED_BY_UNAME = "createdByUname";
    public static final String STATE = "state";
    public static final String REF_ID = "refId";
    public static final String FOLDER = "folder";
    public static final String ELEMENT_COUNT = "elementCount";

    public static final String STEP_GROUP_COUNT = "stepGroupCount";
    public static final String PROGRAM_ELEMENT_COUNT = "programElementCount";
    public static final String EXECUTION_ORDER = "executionOrder";
    public static final String COMMIT = "commit";
    public static final String PUBLISH = "publish";
    public static final String NEW_STATE = "newState";
    public static final String PARENT_ID = "parentId";
    public static final String PARENT_IDS = "parentIds";
    public static final String LOCATORS_COUNT = "locatorsCount";
    public static final String PARENT_NAME = "parentName";
    public static final String LOCATORS = "locators";
    public static final String IS_RECORDED = "isRecorded";
    public static final String LOCATION = "location";
    public static final String CLASS = "_class";
    public static final String ELEMENTS = "elements";
    public static final String ELEMENT_ID = "elementId";
    public static final String TOTAL_ELEMENT_COUNT = "totalElementCount";
    public static final String IS_SHARED = "isShared";
    public static final String CREATED_BY = "createdBy";
    public static final String CREATED_ON = "createdOn";
    public static final String TREE_JSON = "treeJson = ";
    public static final String HIERARCHY = "hierarchy";
    public static final String EXPANDED = "expanded";
    public static final String SCRIPTS_ID = "scripts._id";
    public static final String SCRIPTS_NAME = "scripts.name";
    public static final String SCRIPTS_MODIFIED_ON = "scripts.modifiedOn";
    public static final String SCRIPTS_HIERARCHY = "scripts.hierarchy";
    public static final String SCRIPTS_PARENT_ID = "scripts.parentId";
    public static final String SCRIPTS_EXECUTION_ORDER = "scripts.executionOrder";
    public static final String SCRIPTS_SCRIPT_TYPE = "scripts.scriptType";
    public static final String SCRIPTS_DESC = "scripts.desc";
    public static final String SCRIPTS_CREATED_ON = "scripts.createdOn";
    public static final String MODULE_TREE = "moduleTree";
    public static final String PROJECT_TYPE_IS_MANDATORY = "ProjectType is mandatory";
    public static final String PROJECT_ID_IS_MANDATORY = "ProjectId is mandatory";
    public static final String ACTUAL_PATH = "actualPath";
    public static final String FILES = "files";
    public static final String FILE = "file";
    public static final String ANDROID_LOWERCASE = "android";
    public static final String NUMBER_OF_RESULT_FOUND = "number of result found ";
    public static final String WARNING_UPPERCASE = "WARNING";
    public static final String TWENTYSIX_TO_FIFTY = "26-50";
    public static final String FIFTYONE_TO_SEVENTYFIVE = "51-75";
    public static final String SEVENTYSIX_TO_CENT = "76-100";
    public static final String TERMINATED = "Terminated";
    public static final String ABORTED = "Aborted";
    public static final String SETTING_A_QUERY_TO_FILTER_LICENSEID = "setting a query to filter licenseId : ";
    public static final String PROJECTID = "  projectId :";
    public static final String SUITEID = " and suiteId :";
    public static final String MDC_LICENSEID_KEYWORD = "mdc.licenseId.keyword";
    public static final String MDC_PROJECTID_KEYWORD = "mdc.projectID.keyword";
    public static final String MDC_SUITEID_KEYWORD = "mdc.suiteID.keyword";
    public static final String DOCUMENTS_UPDATED = " documents  Updated";
    public static final String UPGRADE = "Upgrade";
    public static final String DOWNGRADE = "Downgrade";
    public static final String C_PROFESSIONAL = "C-Professional";
    public static final String C_BASIC = "C-Basic";
    public static final String MISSMATCH_IN_PAYMENT_AMOUNT_DETAILS = "Miss-match in Payment amount details : ";
    public static final String DATE_FORMAT = "dd/MM/yyyy HH:mm:ss";
    public static final String RENEW = "Renew";
    public static final String MONTHLY = "Monthly";
    public static final String EMAIL_ID = "emailId";
    public static final String LICENSES_DOT_DOLLAR = "licenses.$.";
    public static final String LICENSES_ID = "licenses._id";
    public static final boolean TRUE = true;
    public static final boolean FALSE = false;
    public static final String TEMPLATE_TYPE = "templateType";
    public static final String PREDEFINED = "Predefined";
    public static final String PRODUCTS = "products";
    public static final String ROLE_ID_IS_MANDATORY = "Role Id is mandatory";
    public static final String PROJECTROLES_DOT_PROJECTID = "projectRoles.projectId";
    public static final String PASSWORD = "password";
    public static final String IS_EXISTING_USER = "isExistingUser";
    public static final String USER_ID_IS_MANDATORY = "User Id is mandatory";
    public static final String EMAIL_ID_IS_MANDATORY = "Email Id is mandatory";
    public static final String EMAIL_ID_DOES_NOT_EXIST = "Email Id does not exist";
    public static final String EMAIL_EXECUTION = "Execution";
    public static final String EMAIL_PROJECT = "Project";
    public static final String EMAIL_NOREPLY = "Noreply";
    public static final String EMAIL_LICENSE = "License";
    public static final String EMAIL_SIGNIN = "Signin";
    public static final String EMAIL_DEFECT = "Defect";
    public static final String ACTIVATION_STATUS = "activationStatus";
    public static final String PASSWORD_TOKEN = "passwordToken";
    public static final String PASSWORD_TOKEN_EXPIRE = "tokenExpireDate";
    public static final String DEFAULT_LICENSE_ID = "defaultLicenseId";
    public static final String LICENSES = "licenses";
    public static final String CONTACT_US = "contactUs";
    public static final String REDIRECT_CONTACT_US_URL = "redirect.contactus.url";
    public static final String LICENSE_IS_MANDATORY = "License is mandatory ";
    public static String PARALLEL_RUN_VALIDATION = "Exceeded your parallel run limit";
    public static final String EXECUTION_ID = "executionId";
    public static final String CLIENT_ID = "clientId";
    public static final String CHILDREN = "children";
    public static final String SCRIPT_TYPE = "scriptType";
    public static final String EXECUTION_RESPONSE = "executionResponses";
    public static final String PLATFORM_STATISTICS = "platformStatistics";
    public static final String SCRIPT_STATS = "scriptStats";
    public static final String MODULE_STATS = "moduleStats";
    public static final String PRE_CONDITION_STATS = "preConditionStats";
    public static final String POST_CONDITION_STATS = "postConditionStats";
    public static final String SUITE_OF_SUITE_NAME = "suiteofSuiteName";
    public static final String DURATION = "Duration";
    public static final String EXECUTED_ON = "ExecutedOn";
    public static final String SUITE_OF_SUITE_STATUS = "suiteofSuiteStatus";
    public static final String EXECUTION_RUN_TYPE = "executionRunType";
    public static final String STEP_RESULTS = "stepResults";
    public static final String PRE_CONDITIONS = "preConditions";
    public static final String POST_CONDITIONS = "postConditions";
    public static final String TAG_DETAILS = "tagDetails";
    public static final String TAGGED_STEP_COUNT = "taggedStepCount";
    public static final String TAG_DETAILS_DTO = "tagDetailsDTOs";
    public static final String STEP_ID = "stepId";
    public static final String WARNING_LOWERCASE = "Warning";
    public static final String SKIPPED = "Skipped";
    public static final String PASSED = "Passed";
    public static final String TITLE = "title";
    public static final String TOTAL_WARNING = "totalWarning";
    public static final String TOTAL_SKIPPED = "totalSkipped";
    public static final String TOTAL_FAILED = "totalFailed";
    public static final String TOTAL_PASSED = "totalPassed";
    public static final String EXECUTION_ENV = "executionEnv";
    public static final String SELECTED_SYSTEM = "selectedSystem";
    public static final String EXECUTION_REPORT = "/ExecutionReport_";
    public static final String OPTIMIZE_PDF_DIR = "optimize.pdf.dir";
    public static final String PRE_CONDITION = "PreCondition";
    public static final String POST_CONDITION = "PostCondition";
    public static final String MODULE_FAILED_MACHINE = "moduleFailedMachine";
    public static final String MODULE_WARNING_MACHINE = "moduleWarningMachine";
    public static final String MODULE_SKIPPED_MACHINE = "moduleSkippedMachine";
    public static final String MODULE_PASSED_MACHINE = "modulePassedMachine";
    public static final String SCRIPT_FAILED_MACHINE = "scriptFailedMachine";
    public static final String SCRIPT_WARNING_MACHINE = "scriptWarningMachine";
    public static final String SCRIPT_SKIPPED_MACHINE = "scriptSkippedMachine";
    public static final String SCRIPT_PASSED_MACHINE = "scriptPassedMachine";
    public static final String PRE_FAILED_MACHINE = "preFailedMachine";
    public static final String PRE_WARNING_MACHINE = "preWarningMachine";
    public static final String PRE_SKIPPED_MACHINE = "preSkippedMachine";
    public static final String PRE_PASSED_MACHINE = "prePassedMachine";
    public static final String POST_FAILED_MACHINE = "postFailedMachine";
    public static final String POST_WARNING_MACHINE = "postWarningMachine";
    public static final String POST_SKIPPED_MACHINE = "postSkippedMachine";
    public static final String POST_PASSED_MACHINE = "postPassedMachine";
    public static final String COLLECTION_BEAN_PARAM = "CollectionBeanParam";
    public static final String MACHINE = "machine";
    public static final String DEVICE_OS = "deviceOs";
    public static final String EXECUTIONID = "executionID";
    public static final String SUITE_NAME = "suiteName";
    public static final String STATUS = "status";
    public static final String DURATION_LOWER_CASE = "duration";
    public static final String EXECUTED_ON_LOWER_CASE = "executedOn";
    public static final String EXECUTION_TYPE = "executionType";
    public static final String SCRIPT_STATS_PARAM = "scriptStatsParam";
    public static final String MODULE_STATS_PARAM = "moduleStatsParam";
    public static final String PRE_CONDITION_STATS_PARAM = "preConditionStatsParam";
    public static final String POST_CONDITION_STATS_PARAM = "postConditionStatsParam";
    public static final String MODULE_FAILED = "moduleFailed";
    public static final String MODULE_WARNING = "moduleWarning";
    public static final String MODULE_SKIPPED = "moduleSkipped";
    public static final String MODULE_PASSED = "modulePassed";
    public static final String SCRIPT_FAILED = "scriptFailed";
    public static final String SCRIPT_WARNING = "scriptWarning";
    public static final String SCRIPT_SKIPPED = "scriptSkipped";
    public static final String SCRIPT_PASSED = "scriptPassed";
    public static final String PRE_FAILED = "preFailed";
    public static final String PRE_WARNING = "preWarning";
    public static final String PRE_SKIPPED = "preSkipped";
    public static final String PRE_PASSED = "prePassed";
    public static final String POST_FAILED = "postFailed";
    public static final String POST_WARNING = "postWarning";
    public static final String POST_SKIPPED = "postSkipped";
    public static final String POST_PASSED = "postPassed";
    public static final String SCRIPT_CHART_TOTAL = "scriptChartTotal";

    public static String OS = "os";
    public static final String TOTAL = "total";

    public static final String MODULE_CHART_TOTAL = "moduleChartTotal";
    public static final String PRE_CHART_TOTAL = "preChartTotal";
    public static final String POST_CHART_TOTAL = "postChartTotal";
    public static final String FAILED_LOWER_CASE = "failed";
    public static final String SKIPPED_LOWER_CASE = "skipped";

    public static final String PASSED_LOWER_CASE = "passed";
    public static final String POST_FAILED_WIDTH = "postFailedWidth";
    public static final String CHART_TOTAL_X = "chartTotalX";
    public static final String SCRIPT_ZERO = "Script(0)";
    public static final String CHART_X = "chartX";
    public static final String PARAMS = "params";
    public static final String JRXML = "jrxml";

    public static final String OAUTH1 = "Oauth1";
    public static final String OAUTH2 = "Oauth2";
    public static final String BEARER_AUTH_TOKEN = "Bearer";
    public static final String registeredFrom = "FireSpiders";
    public static final String GRIDFSLOGGERMSG = "reaches the GridFS";
    public static final String NOT_FOUND = "NOT_FOUND";
    public static final long FILE_SIZE = 16793600;
    public static final String GRIDFS_REF = "GridFS";
    public static final String S3_REF = "Amazon_S3";
    public static final String RESULT_SUFFIX = "-Result";
    public static final String Successfully_Purchased_CBasic_License = "Successfully purchased C-Basic License";
    public static final String Successfully_Purchased_CProf_License = "Successfully purchased C-Professional License";
    public static final String Successfully_Upgraded_CProf_License = "Successfully Upgraded C-Professional License";
    public static final String Successfully_Downgraded_CProf_License = "Successfully Downgraded C-Professional License";
    public static final String Successfully_Renewed_CProf_License = "Successfully Renewed C-Professional License";

    public static final String DEVICE_OS_STRING = "Device OS";
    public static final String BROWSER_STRING="Browser";
    public static final String DEVICE_STRING="Device";
    public static final String MACHINE_STRING="Machine";
    public static final String EXECUTION_ID_STRING="Execution ID";
    public static final String SUITE_NAME_STRING="Suite Name";
    public static final String STATUS_STRING="Status";
    public static final String EXECUTION_TYPE_STRING="Execution Type";
    public static final String EXECUTION_ON_STRING="Executed On";
    public static final String MODULES_STRING="Modules:";
    public static final String SCRIPTS_STRING="Scripts:";
    public static final String PRE_CONDITIONS_STRING="PreConditions:";
    public static final String POST_CONDITIONS_STRING="PostConditions:";
    public static final String FAILED_STRING="Failed(";
    public static final String WARNING_STRING="Warning(";
    public static final String SKIPPED_STRING="Skipped(";
    public static final String PASSED_STRING="Passed(";
    public static final String NOT_EXECUTED_STRING="Not Executed(";
    public static final String PARTIALLY_EXECUTED_STRING="Partially Executed(";
    public static final String USER_STRING="User";
    public static final String TOTAL_USERS_STRING="Total Users";
    public static final String EXECUTION_ENVIRONMENT_STRING="Execution Environment";
    public static final String TOTAL_DURATION_STRING="Total Duration";
    public static final String PARTIALLY_EXECUTED_STRING_STYLE="Partially Executed";
    public static final String NOT_EXECUTED_STRING_STYLE="Not Executed";
    public static final String TERMINATED_STRING_STYLE="Terminated";
    public static final String ABORTED_STRING_STYLE="Aborted";
    public static final String SKIPPED_STRING_STYLE="Skipped";
    public static final String WARNING_STRING_STYLE="Warning";
    public static final String PASSED_STRING_STYLE="Passed";
    public static final String FAILED_STRING_STYLE="Failed";
    public static final String VALIDATE_RESOURCE_NAME_PATTERN = "^[-a-zA-Z0-9-()_]+(\\s+[-a-zA-Z0-9-()_]+)*$";

    //variable related constant
    public static final String PARENT_VARIABLE_ID = "parentVariableId";
    public static final String SUB_PARENT_VARIABLE_ID = "subParentVariableId";
    public static final String PARENT_VARIABLE_TYPE = "parentVariableType";
    public static final String MODULE = "MODULE";
    public static final List<String> parentVariableTypesList = Arrays.asList(MODULE, WSWB);

    public static final String IF_CHECK_POINT_IS_FAILED = "ifCheckPointIsFailed";
    public static final String CONTAINS_CHILD_NLP = "containsChildNlp";
    public static final String ELEMENT_NAME = "elementName";
    public static final String ELEMENT_NAME_REGEX = "*elementName*";
    public static final String ELEMENT_TYPE = "elementType";
    public static final String ELEMENT_TYPE_REGEX = "*elementType*";
    public static final String ELEMENT = "element";
    public static final String EXPLICIT_TIME_OUT = "explicitTimeOut";
    public static final String TEXT = "text";
    public static final String TEXT_REGEX = "*text*";
    public static final String LOCATOR_TYPE = "locatorType";
    public static final String LOCATOR_TYPE_REGEX = "*locatorType*";
    public static final String LOCATOR_VALUE = "locatorValue";
    public static final String LOCATOR_VALUE_REGEX = "*locatorValue*";
    public static final String ATTRIBUTE = "attribute";
    public static final String ATTRIBUTE_REGEX = "*attribute*";
    public static final String TIME = "time";
    public static final String VALUE_REGEX = "*value*";
    public static final String ELEMENTS_REGEX = "*elements*";
    public static final String IMPLICIT_TIME_OUT = "implicitTimeOut";
    public static final String DATA = "data";
    public static final String RESULT_DATA_TYPE = "resultDataType";
    public static final String DATA_REGEX = "*data*";
    public static final String RESULT_DATA_TYPE_REGEX = "*resultDataType*";
    public static final String STRING_1 = "string1";
    public static final String STRING_2 = "string2";
    public static final String STRING_1_REGEX = "*string1*";
    public static final String STRING_2_REGEX = "*string2*";
    public static final String DB_URL1 = "dbURL";
    public static final String USERNAME = "username";
    public static final String TABLE_NAME = "tableName";
    public static final String CONDITION = "condition";
    public static final String TABLE_NAME_REGEX = "*tableName*";
    public static final String CONDITION_REGEX = "*condition*";
    public static final String COLUMNS = "columns";
    public static final String INSERT_VALUES = "insertValues";
    public static final String INSERT_VALUES_REGEX = "*insertValues*";
    public static final String SET_VALUES = "setValues";
    public static final String SET_VALUES_REGEX = "*setValues*";
    public static final String DB_URL = "dbUrl";
    public static final String FIND_COLUMNS = "findColumns";
    public static final String JDBC_CLASSNAME = "com.mysql.jdbc.Driver";
    public static final String POSTGRESQL_CLASSNAME = "org.postgresql.Driver";
    public static final String BLANK = "BLANK";
    public static final String BOOLEAN = "BOOLEAN";
    public static final String STRING = "STRING";
    public static final String NUMERIC = "NUMERIC";
    public static final String FORMULA = "FORMULA";
    public static final String DATE_FORMAT_DD_MM_YYYY = "dd-MM-yyyy";
    public static final int ONE_MB_IN_BYTE = 1048576;
    public static final String SPRING_MAIL_USERNAME = "spring.mail.username";
    public static final String SPRING_MAIL_PASSWORD = "spring.mail.password";
    public static final String SPRING_EXECUTION_MAIL_USERNAME = "spring.execution.mail.username";
    public static final String SPRING_PROJECT_MAIL_USERNAME = "spring.project.mail.username";
    public static final String SPRING_LICENSE_MAIL_USERNAME = "spring.license.mail.username";
    public static final String SPRING_DEFECT_MAIL_USERNAME = "spring.defect.mail.username";
    public static final String SPRING_NOREPLY_MAIL_USERNAME = "spring.noreply.mail.username";

    public static final String SPRING_SIGNIN_MAIL_USERNAME = "spring.signin.mail.username";
    public static final String AUTO_RUN_TYPE = "auto";
    public static final String EXEC_REQUEST_FOLDER = "Request/";
    public static final String EXEC_RESPONSE_FOLDER = "Response/";
    public static final String NO_REPLY = "no_reply";
    public static final String NO_REPLY_MAIL_USERNAME = "no.reply.mail.username";
    public static final String CONTACT_US_MAIL_USERNAME = "contact.us.mail.username";
    public static final String DEMO_MAIL_USERNAME = "demo.mail.username";

}
